MODULE = DCM_module
MODULE_NAME = motor_left

PACKAGES = led

PRJ_CPPSRC = \
	nodes/encoder_node.cpp \
	nodes/current_pid_node.cpp \
	nodes/calibration_node.cpp \
	main.cpp

include $(R2P_ROOT)/core/r2p.mk

