MODULE = GW_module
MODULE_NAME = GW_basketbot

PACKAGES = led

PRJ_CSRC = \
	misc/urosUser.c \
	misc/urosMsgTypes.c

PRJ_CPPSRC = \
    misc/urosHandlers.cpp \
    callbacks.cpp \
	main.cpp
	
UINCDIR = misc

include $(R2P_ROOT)/core/r2p.mk

